pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'GTNH Maven'
            url = 'https://nexus.gtnewhorizons.com/repository/public/'
        }
    }
}

// Auto-resolver скачивает недостающие JDK-версии (например JDK 8 для
// компиляции patched MC) с foojay.io автоматически.
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'PriceDump'
